version: "3.4"

services:
  db:
    container_name: "db"
    logging:
      driver: none
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root_db!
        - MONGO_INITDB_DATABASE=admin
    command: ["--auth", "--quiet", "--bind_ip_all"]
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - crypto_dca_db:/data/db

  api:
    container_name: "api"
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - COOKIE_SECRET=2x4tTxQ7jRHqLRl8bbFYoUADDLbyfcNh
      - JWT_SECRET=De3Y6aKGywtQzWl7c0e4hYslK1lRb85u
      - HTTP_PORT=5000
      - MONGO_URI=mongodb://admin:admin_passwd@db:27017/crypto-dca
    volumes:
      - ./server:/app
    ports:
      - 5000:5000

  # client:
  #   stdin_open: true
  #   container_name: "client"
  #   depends_on:
  #     - api
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./client:/app
  #   ports:
  #     - "3000:3000"

volumes:
  crypto_dca_db:
    driver: local
