version: "3.4"

services:
  db:
    container_name: "swealy-db"
    image: ghcr.io/jessy-bgl/swealy-db:stable
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_db!
      - MONGO_INITDB_DATABASE=admin
    command: ["--auth"]
    volumes:
      - swealy_db:/data/db
    restart: unless-stopped

  api:
    container_name: "swealy-api"
    image: ghcr.io/jessy-bgl/swealy-api:stable
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    environment:
      - COOKIE_SECRET=2x4tTxQ7jRHqLRl8bbFYoUADDLbyfcNh
      - JWT_SECRET=De3Y6aKGywtQzWl7c0e4hYslK1lRb85u
      - MONGO_URI=mongodb://admin:swealyAdminPasswd@db:27017/swealy
    restart: unless-stopped
    depends_on:
      - db

  client:
    container_name: "swealy-client"
    image: ghcr.io/jessy-bgl/swealy-client:stable
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - api

  proxy:
    container_name: "swealy-proxy"
    image: ghcr.io/jessy-bgl/swealy-proxy:stable
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - client
    ports:
      - 80:80
      - 443:443

volumes:
  swealy_db:
    driver: local
