name: Docker Image CI

on:
  push:
    branches: [dev/ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push client
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: client
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jessy-bgl/swealy:latest
            ghcr.io/jessy-bgl/swealy:latest

        # - uses: actions/checkout@v2
        # - name: Build the client Docker image
        #   run: cd client && docker build . --file Dockerfile --tag swealy-client:1.0.0-beta1

#      env:
#        CI: false
