name: Docker Image CI

on:
  release:
    types: ["published"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest client
        uses: docker/build-push-action@v2
        with:
          context: client
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jessy-bgl/swealy-client:latest

      - name: Build and push latest api
        uses: docker/build-push-action@v2
        with:
          context: server
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jessy-bgl/swealy-api:latest

      - name: Build and push latest database
        uses: docker/build-push-action@v2
        with:
          context: database
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jessy-bgl/swealy-db:latest

      - name: Build and push latest proxy
        uses: docker/build-push-action@v2
        with:
          context: proxy
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jessy-bgl/swealy-proxy:latest

      - name: Build and push stable client
        if: ${{ !github.event.release.prerelease }}
        uses: docker/build-push-action@v2
        with:
          context: client
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jessy-bgl/swealy-client:stable

      - name: Build and push stable api
        if: ${{ !github.event.release.prerelease }}
        uses: docker/build-push-action@v2
        with:
          context: server
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jessy-bgl/swealy-api:stable

      - name: Build and push stable database
        if: ${{ !github.event.release.prerelease }}
        uses: docker/build-push-action@v2
        with:
          context: database
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jessy-bgl/swealy-db:stable

      - name: Build and push stable proxy
        if: ${{ !github.event.release.prerelease }}
        uses: docker/build-push-action@v2
        with:
          context: proxy
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jessy-bgl/swealy-proxy:stable
